CLASS ycl_addict_dol_obj_enhc DEFINITION
  INHERITING FROM ycl_addict_dol_obj_enho
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS YCL_ADDICT_DOL_OBJ_ENHC IMPLEMENTATION.
ENDCLASS.
